package com.btg.claro.lbs.ws;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;

/**
 * This class was generated by the JAX-WS RI. JAX-WS RI 2.1.3-hudson-390-
 * Generated source version: 2.0
 * 
 */
@WebService(name="LBSConsultaService",targetNamespace="http://endpoint.ws.LBS.claro.btg.com/")
public interface LBSConsultaService{

	/**
	 * 
	 * @param parametro
	 * @return returns com.btg.claro.lbs.ws.endpoint.ResultadoConsulta
	 */
	@WebMethod
	@WebResult(targetNamespace="")
	@RequestWrapper(localName="consultaLBS",targetNamespace="http://endpoint.ws.LBS.claro.btg.com/",className="com.btg.claro.lbs.ws.ConsultaLBS")
	@ResponseWrapper(localName="consultaLBSResponse",targetNamespace="http://endpoint.ws.LBS.claro.btg.com/",className="com.btg.claro.lbs.ws.ConsultaLBSResponse")
	public ResultadoConsulta consultaLBS(@WebParam(name="parametro",targetNamespace="") ParametroConsulta parametro);

	/**
	 * 
	 * @param telefono
	 * @return returns java.lang.String
	 */
	@WebMethod
	@WebResult(targetNamespace="")
	@RequestWrapper(localName="obtenerUbicacion",targetNamespace="http://endpoint.ws.LBS.claro.btg.com/",className="com.btg.claro.lbs.ws.ObtenerUbicacion")
	@ResponseWrapper(localName="obtenerUbicacionResponse",targetNamespace="http://endpoint.ws.LBS.claro.btg.com/",className="com.btg.claro.lbs.ws.ObtenerUbicacionResponse")
	public String obtenerUbicacion(@WebParam(name="telefono",targetNamespace="") String telefono);

}
