package com.stconsulting.lbsws.ws;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;

/**
 * This class was generated by the JAX-WS RI. JAX-WS RI 2.1.3-hudson-390-
 * Generated source version: 2.0
 * 
 */
@WebService(name = "LBSEndpointService", targetNamespace = "http://endpoint.ws.LBS.claro.btg.com/")
public interface LBSConsultaService {

	/**
	 * 
	 * @param arg0
	 * @return returns com.stconsulting.lbsws.ws.ResultadoConsulta
	 */
	@WebMethod
	@WebResult(targetNamespace = "")
	@RequestWrapper(localName = "consultaLBS", targetNamespace = "http://endpoint.ws.LBS.claro.btg.com/", className = "com.stconsulting.lbsws.ws.ConsultaLBS")
	@ResponseWrapper(localName = "consultaLBSResponse", targetNamespace = "http://endpoint.ws.LBS.claro.btg.com/", className = "com.stconsulting.lbsws.ws.ConsultaLBSResponse")
	public ResultadoConsulta consultaLBS(@WebParam(name = "parametro", targetNamespace = "") ParametroConsulta arg0);


    /**
     * 
     * @param password
     * @param numeroDestino
     */
    @WebMethod
    @RequestWrapper(localName = "enviarPasswordSMS", targetNamespace = "http://endpoint.ws.LBS.claro.btg.com/", className = "com.stconsulting.lbsws.ws.EnviarPasswordSMS")
    @ResponseWrapper(localName = "enviarPasswordSMSResponse", targetNamespace = "http://endpoint.ws.LBS.claro.btg.com/", className = "com.stconsulting.lbsws.ws.EnviarPasswordSMSResponse")
    public void enviarPasswordSMS(
        @WebParam(name = "numeroDestino", targetNamespace = "")
        String numeroDestino,
        @WebParam(name = "password", targetNamespace = "")
        String password);
}
